### ISSUE TITLE
Project initialization failed on windows machines on missing `sed` command

### ISSUE THREAD

**Issue by miroslavpojer** [AbsaOSS/spark-data-standardization#31]
## Describe the bug
On windows machines the initialization (call `sbt` in command line) failed due to missing command `sed` on windows.

## Expected behavior
Call sbt will work.

## Desktop (please complete the following information):
 - OS: Windows

## Additional context
**Partial output with an errors.**

    [info] loading settings for project spark-data-standardization from build.sbt,publish.sbt ...
    Exception in thread "Thread-15" java.io.IOException: Cannot run program "sed": CreateProcess error=2, The system cannot find the file specified        
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)        
    at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)        
    at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:142)        
    at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:121)        
    at scala.sys.process.ProcessImpl$CompoundProcess.$anonfun$x$4$1(ProcessImpl.scala:100)        
    at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:27)

**Workaround**
Comment lines below in file `build.sbt`

    lazy val currBranchName = "git branch --show-current".!!.trim
    lazy val baseBranchName = (
      "git show-branch -a"
        #| raw"grep \*"
        #| s"grep -v $currBranchName"
        #| "head -n1"
        #| raw"sed s/.*\[\(.*\)\].*/\1/"
    ).!!.trim
    scalafmtFilter.withRank(KeyRanks.Invisible) := s"diff-ref=${baseBranchName}

**Proposal to solve**

    lazy val currBranchName = "git branch --show-current".!!.trim
    lazy val baseBranchName = System.getProperty("os.name").toLowerCase match {
      case win if win.contains("win") =>
        ???           **<find alternative solution for windows>**
      case osName =>
        (
          "git show-branch -a"
            #| raw"grep \*"
            #| s"grep -v $currBranchName"
            #| "head -n1"
            #| raw"sed s/.*\[\(.*\)\].*/\1/"
          ).!!.trim
    }

**Comment by miroslavpojer** [comment]
This bug issue has been solved by PR #33

**Comment by miroslavpojer** [comment]
This bug issue has been solved by PR #33
