### ISSUE TITLE
Sandardization fails when data does not match date pattern

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/spark-data-standardization#55]
## Describe the bug
This error happens when the date pattern does not match the field value.

In this example, the source data type is `integer`, the target data type is `date`.

```
org.apache.spark.SparkException: Job aborted.
  org.apache.spark.sql.errors.QueryExecutionErrors$.jobAbortedError(QueryExecutionErrors.scala:638)
  org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:279)
  org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:193)
  org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
  org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
  org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
  org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:103)
  org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
  org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
  org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:114)
  org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$7(SQLExecution.scala:139)
  org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
  org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
  org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:139)
  org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
  org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:138)
  org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
  org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
  org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:100)
  org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:96)
  org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:615)
  org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:177)
  org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:615)
  org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
  org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
  org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
  org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:591)
  org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:96)
  org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:83)
  org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:81)
  org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:124)
  org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
  org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
  org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
  org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
  org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:793)
  za.co.absa.pramen.core.metastore.peristence.TransientTableManager$.addPersistedDataFrame(TransientTableManager.scala:83)
  za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransientEager.saveTable(MetastorePersistenceTransientEager.scala:53)
  za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.saveTable(MetastorePersistenceTransient.scala:49)
  za.co.absa.pramen.core.metastore.MetastoreImpl.saveTable(MetastoreImpl.scala:95)
  za.co.absa.pramen.core.pipeline.TransformationJob.save(TransformationJob.scala:66)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$run$1(TaskRunnerBase.scala:325)
  scala.util.Try$.apply(Try.scala:213)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.run(TaskRunnerBase.scala:281)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.runLazyTask(TaskRunnerBase.scala:91)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runJob(TransientJobManager.scala:225)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.$anonfun$getLazyTaskFuture$1(TransientJobManager.scala:156)
  scala.util.Try$.apply(Try.scala:213)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.getLazyTaskFuture(TransientJobManager.scala:156)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runLazyTask(TransientJobManager.scala:121)
  za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.loadTable(MetastorePersistenceTransient.scala:38)
  za.co.absa.pramen.core.metastore.MetastoreImpl.getTable(MetastoreImpl.scala:75)
  za.co.absa.pramen.core.metastore.MetastoreImpl$$anon$1.getTable(MetastoreImpl.scala:182)
  za.co.absa.ingestionaas.pramen.components.transformers.NormalizationTransformer.validate(NormalizationTransformer.scala:65)
  za.co.absa.pramen.core.pipeline.TransformationJob.validate(TransformationJob.scala:48)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$validate$1(TaskRunnerBase.scala:236)
  scala.util.Try$.apply(Try.scala:213)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.validate(TaskRunnerBase.scala:236)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.runLazyTask(TaskRunnerBase.scala:89)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runJob(TransientJobManager.scala:225)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.$anonfun$getLazyTaskFuture$1(TransientJobManager.scala:156)
  scala.util.Try$.apply(Try.scala:213)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.getLazyTaskFuture(TransientJobManager.scala:156)
  za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runLazyTask(TransientJobManager.scala:121)
  za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.loadTable(MetastorePersistenceTransient.scala:38)
  za.co.absa.pramen.core.metastore.MetastoreImpl.getTable(MetastoreImpl.scala:75)
  za.co.absa.pramen.core.metastore.MetastoreImpl$$anon$1.getTable(MetastoreImpl.scala:182)
  za.co.absa.ingestionaas.pramen.components.transformers.SimpleFlatteningTransformer.run(SimpleFlatteningTransformer.scala:81)
  za.co.absa.pramen.core.pipeline.TransformationJob.run(TransformationJob.scala:52)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$run$1(TaskRunnerBase.scala:289)
  scala.util.Try$.apply(Try.scala:213)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.run(TaskRunnerBase.scala:281)
  za.co.absa.pramen.core.runner.task.TaskRunnerBase.runTask(TaskRunnerBase.scala:126)
  za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.$anonfun$runParallel$3(TaskRunnerMultithreaded.scala:93)
  za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.whenEnoughResourcesAreAvailable(TaskRunnerMultithreaded.scala:66)
  za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.$anonfun$runParallel$2(TaskRunnerMultithreaded.scala:91)
  scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
  scala.util.Success.$anonfun$map$1(Try.scala:255)
  scala.util.Success.map(Try.scala:213)
  scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
  scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
  scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
  scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:750)

  Caused by org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 18.0 failed 4 times, most recent failure: Lost task 0.3 in stage 18.0 (TID 13) (10.233.155.200 executor 1): org.apache.spark.SparkException: Task failed while writing rows.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:642)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:349)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:257)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:138)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.SparkUpgradeException: You may get a different result due to the upgrading to Spark >= 3.0: Fail to parse '2582097' in the new parser. You can set spark.sql.legacy.timeParserPolicy to LEGACY to restore the behavior before Spark 3.0, or set to CORRECTED and treat it as an invalid datetime string.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.failToParseDateTimeInNewParserError(QueryExecutionErrors.scala:1066)
	at org.apache.spark.sql.catalyst.util.DateTimeFormatterHelper$$anonfun$checkParsedDiff$1.applyOrElse(DateTimeFormatterHelper.scala:148)
	at org.apache.spark.sql.catalyst.util.DateTimeFormatterHelper$$anonfun$checkParsedDiff$1.applyOrElse(DateTimeFormatterHelper.scala:141)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.spark.sql.catalyst.util.Iso8601TimestampFormatter.parse(TimestampFormatter.scala:176)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.Cast_4$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CaseWhen_453$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CreateNamedStruct_10$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.createNamedStruct_15_1$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20_7$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:332)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1550)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:339)
	... 9 more
Caused by: java.time.format.DateTimeParseException: Text '2582097' could not be parsed at index 6
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
	at org.apache.spark.sql.catalyst.util.Iso8601TimestampFormatter.parse(TimestampFormatter.scala:168)
	... 23 more

Driver stacktrace:
    org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2863)
    org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2799)
    org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2798)
    scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
    scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
    scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
    org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2798)
    org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1239)
    org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1239)
    scala.Option.foreach(Option.scala:407)
    org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1239)
    org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3051)
    org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2993)
    org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2982)
    org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
    org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1009)
    org.apache.spark.SparkContext.runJob(SparkContext.scala:2229)
    org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:246)
    org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:193)
    org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
    org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
    org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
    org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:103)
    org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
    org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
    org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:114)
    org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$7(SQLExecution.scala:139)
    org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
    org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
    org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:139)
    org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
    org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:138)
    org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
    org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
    org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:100)
    org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:96)
    org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:615)
    org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:177)
    org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:615)
    org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
    org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
    org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
    org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
    org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
    org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:591)
    org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:96)
    org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:83)
    org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:81)
    org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:124)
    org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
    org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
    org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
    org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
    org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:793)
    za.co.absa.pramen.core.metastore.peristence.TransientTableManager$.addPersistedDataFrame(TransientTableManager.scala:83)
    za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransientEager.saveTable(MetastorePersistenceTransientEager.scala:53)
    za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.saveTable(MetastorePersistenceTransient.scala:49)
    za.co.absa.pramen.core.metastore.MetastoreImpl.saveTable(MetastoreImpl.scala:95)
    za.co.absa.pramen.core.pipeline.TransformationJob.save(TransformationJob.scala:66)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$run$1(TaskRunnerBase.scala:325)
    scala.util.Try$.apply(Try.scala:213)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.run(TaskRunnerBase.scala:281)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.runLazyTask(TaskRunnerBase.scala:91)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runJob(TransientJobManager.scala:225)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.$anonfun$getLazyTaskFuture$1(TransientJobManager.scala:156)
    scala.util.Try$.apply(Try.scala:213)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.getLazyTaskFuture(TransientJobManager.scala:156)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runLazyTask(TransientJobManager.scala:121)
    za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.loadTable(MetastorePersistenceTransient.scala:38)
    za.co.absa.pramen.core.metastore.MetastoreImpl.getTable(MetastoreImpl.scala:75)
    za.co.absa.pramen.core.metastore.MetastoreImpl$$anon$1.getTable(MetastoreImpl.scala:182)
    za.co.absa.ingestionaas.pramen.components.transformers.NormalizationTransformer.validate(NormalizationTransformer.scala:65)
    za.co.absa.pramen.core.pipeline.TransformationJob.validate(TransformationJob.scala:48)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$validate$1(TaskRunnerBase.scala:236)
    scala.util.Try$.apply(Try.scala:213)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.validate(TaskRunnerBase.scala:236)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.runLazyTask(TaskRunnerBase.scala:89)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runJob(TransientJobManager.scala:225)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.$anonfun$getLazyTaskFuture$1(TransientJobManager.scala:156)
    scala.util.Try$.apply(Try.scala:213)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.getLazyTaskFuture(TransientJobManager.scala:156)
    za.co.absa.pramen.core.metastore.peristence.TransientJobManager$.runLazyTask(TransientJobManager.scala:121)
    za.co.absa.pramen.core.metastore.peristence.MetastorePersistenceTransient.loadTable(MetastorePersistenceTransient.scala:38)
    za.co.absa.pramen.core.metastore.MetastoreImpl.getTable(MetastoreImpl.scala:75)
    za.co.absa.pramen.core.metastore.MetastoreImpl$$anon$1.getTable(MetastoreImpl.scala:182)
    za.co.absa.ingestionaas.pramen.components.transformers.SimpleFlatteningTransformer.run(SimpleFlatteningTransformer.scala:81)
    za.co.absa.pramen.core.pipeline.TransformationJob.run(TransformationJob.scala:52)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.$anonfun$run$1(TaskRunnerBase.scala:289)
    scala.util.Try$.apply(Try.scala:213)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.run(TaskRunnerBase.scala:281)
    za.co.absa.pramen.core.runner.task.TaskRunnerBase.runTask(TaskRunnerBase.scala:126)
    za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.$anonfun$runParallel$3(TaskRunnerMultithreaded.scala:93)
    za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.whenEnoughResourcesAreAvailable(TaskRunnerMultithreaded.scala:66)
    za.co.absa.pramen.core.runner.task.TaskRunnerMultithreaded.$anonfun$runParallel$2(TaskRunnerMultithreaded.scala:91)
    scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
    scala.util.Success.$anonfun$map$1(Try.scala:255)
    scala.util.Success.map(Try.scala:213)
    scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:750)

    Caused by org.apache.spark.SparkException: Task failed while writing rows.
      org.apache.spark.sql.errors.QueryExecutionErrors$.taskFailedWhileWritingRowsError(QueryExecutionErrors.scala:642)
      org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:349)
      org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:257)
      org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
      org.apache.spark.scheduler.Task.run(Task.scala:138)
      org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
      org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
      org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
      java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      java.lang.Thread.run(Thread.java:750)

      Caused by org.apache.spark.SparkUpgradeException: You may get a different result due to the upgrading to Spark >= 3.0: Fail to parse '2582097' in the new parser. You can set spark.sql.legacy.timeParserPolicy to LEGACY to restore the behavior before Spark 3.0, or set to CORRECTED and treat it as an invalid datetime string.
        org.apache.spark.sql.errors.QueryExecutionErrors$.failToParseDateTimeInNewParserError(QueryExecutionErrors.scala:1066)
        org.apache.spark.sql.catalyst.util.DateTimeFormatterHelper$$anonfun$checkParsedDiff$1.applyOrElse(DateTimeFormatterHelper.scala:148)
        org.apache.spark.sql.catalyst.util.DateTimeFormatterHelper$$anonfun$checkParsedDiff$1.applyOrElse(DateTimeFormatterHelper.scala:141)
        scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        org.apache.spark.sql.catalyst.util.Iso8601TimestampFormatter.parse(TimestampFormatter.scala:176)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.Cast_4$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CaseWhen_453$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CreateNamedStruct_10$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.createNamedStruct_15_1$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20_7$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20$(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
        org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
        scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
        org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
        org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:332)
        org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1550)
        org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:339)
        org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:257)
        org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        org.apache.spark.scheduler.Task.run(Task.scala:138)
        org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
        org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        java.lang.Thread.run(Thread.java:750)

        Caused by java.time.format.DateTimeParseException: Text '2582097' could not be parsed at index 6
          java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
          java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1777)
          org.apache.spark.sql.catalyst.util.Iso8601TimestampFormatter.parse(TimestampFormatter.scala:168)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.Cast_4$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CaseWhen_453$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.CreateNamedStruct_10$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_0.createNamedStruct_15_1$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20_7$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection$NestedClass_3.writeFields_20$(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
          org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
          scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
          scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
          org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:92)
          org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:332)
          org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1550)
          org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:339)
          org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:257)
          org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
          org.apache.spark.scheduler.Task.run(Task.scala:138)
          org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
          org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
          org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
          java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          java.lang.Thread.run(Thread.java:750)
```

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Create a target schema with `integer` to `date` conversion rules.
2. Specify a pattern that does not match the data, or add data that does not match the pattern (pattern=`yyyyMMdd`, value=`2582097`)
3. Run the standardization

## Expected behavior
Standardization should not fail on data errors. It should populate the error column instead.

## Screenshots
--

## Desktop (please complete the following information):
--

## Additional context
--

**Comment by yruslan** [comment]
Seems to be solved using:
```hocon
spark.sql.legacy.timeParserPolicy = "CORRECTED"
```

Will close the issue once confirmed

**Comment by yruslan** [comment]
Solved itself as above 😆
